import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Script from "next/script";   

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Traits Global Solutions",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        
       
        <Script
          src="https://kit.fontawesome.com/17edda2936.js"
          crossOrigin="anonymous"
        />

        {children}
      </body>
    </html>
  );
}
